### ISSUE TITLE
"Background permission revoked" error when starting up

### ISSUE THREAD

**Issue by lyndonguitar** [zocker-160/SyncThingy#10]
It shows an error,
"Background permission revoked"
SyncThingy might not work as expected

I cannot find a way of granting permission within the Linux SteamOS system

I used stable and preview branches of SteamOS as of today

**Comment by lyndonguitar** [comment]
Okay silly me, I just posted there without checking the closed issues. On the closed issues there is actually a solution for this already https://github.com/zocker-160/SyncThingy/issues/6#issuecomment-1238181904

**Comment by zocker-160** [comment]
yeah this is sadly something that Valve messed up with the latest Steam OS 3.3.2 update see #7 and https://github.com/zocker-160/SyncThingy/issues/7#issuecomment-1290182529
