### ISSUE TITLE
Cannot install as service

### ISSUE THREAD

**Issue by darrenltw** [zocker-160/SyncThingy#22]
wget https://raw.githubusercontent.com/zocker-160/SyncThingy/master/linux_packaging

Returned 400 bad request, please help!!!

**Comment by zocker-160** [comment]
This could be a temporary issue with GitHub 

I can access the url `https://raw.githubusercontent.com/zocker-160/SyncThingy/master/linux_packaging/syncthingy.service` without issues.

Could you please check that you can reach that url on your device?

**Comment by darrenltw** [comment]
Maybe the problem was on my side, I tried again this morning and it worked.

Thanks for your prompt response!

*Regards, *




*Darren *
