### ISSUE TITLE
Reset Syncthing database

### ISSUE THREAD

**Issue by alondero** [zocker-160/SyncThingy#23]
I have some invalid out of sync issues in Syncthing. According to the Syncthing docs I'd need to start up Syncthing with a '--reset-database' command, but unsure how to do this with this Flatpak-ed version (I couldn't find the Flatpak in the flatpak/apps or flatpak/exports/bin folder.

Any advice?

**Comment by zocker-160** [comment]
`flatpak run --command=syncthing com.github.zocker_160.SyncThingy --reset-database` should do.
