### ISSUE TITLE
Not getting latest version of Syncthing on install

### ISSUE THREAD

**Issue by protoz** [zocker-160/SyncThingy#24]
This may be a holdover from using the old Syncthing GTK flatpak but after uninstalling that and installing Syncthingy, I am still running version 1.23 instead of the latest 1.27.1 where auto-upgrade is disabled.

Is that intentional or can I run a command to resolve this?

**Comment by protoz** [comment]
Nevermind, I restarted and it started your version on latest

**Comment by zocker-160** [comment]
I just want to add for anybody experiencing this:

SyncThingy will attach to any already running syncthing instance and not start its own. So if an older version still runs in the background, it will not try to replace it.

As for the updates: I am keeping the Flatpak up to date with the latest stable releases of syncthing and I will push the updates without increasing the version number of SyncThingy, so it will not show in the Flathub changelogs.
