### ISSUE TITLE
[STEAM DECK] Syncthing failed to start! exit code (1) 

### ISSUE THREAD

**Issue by Philipoo0** [zocker-160/SyncThingy#26]
Hello,

On steamDeck after installing background service

mkdir -p ~/.config/systemd/user 
wget https://raw.githubusercontent.com/zocker-160/SyncThingy/master/linux_packaging/syncthingy.service -O ~/.config/systemd/user/syncthingy.service 
systemctl --user enable --now syncthingy

Syncthing start correctly on gaming mode but I get an error when switching to desktop mode
Syncthing failed to start! exit code (1) 

It looks like it is a tray indicator issue only as the server is running despite the error, but i do not have the icon 
I have HTTPS enabled in the server and autostart option activated in the syncthingy setting

Thanks in advance

**Comment by zocker-160** [comment]
did you also set the url in the setting to HTTPS?

**Comment by Philipoo0** [comment]
Indeed, it was the problem. Issue is solved. Thanks a lot for your job !
