### ISSUE TITLE
Where exactly can I find my Syncthing configuration?

### ISSUE THREAD

**Issue by MultiKoopa** [zocker-160/SyncThingy#29]
I setup Syncthingy a while ago on my Steam Deck, and I'm trying to find the actual configuration files for Syncthing (like all the folders, all the sync states, etc.)

~/.local/state/syncthing is blank, and ~/.var/app/com.github.zocker_160.SyncThingy/config/syncthing only has a tiny little config file with: 

"[General]
autostart=false
icon=color
notifications=true
url=http://127.0.0.1:8384"

where is everything else stored?

**Comment by zocker-160** [comment]
Syncthing config is located at `~/.var/app/com.github.zocker_160.SyncThingy/config/syncthing/config.xml`.

**Comment by MultiKoopa** [comment]
> Syncthing config is located at `~/.var/app/com.github.zocker_160.SyncThingy/config/syncthing/config.xml`.

....right, but there's almost nothing in that. Where's all of Syncthing's settings? Which folders to sync, sync states, etc.

**Comment by zocker-160** [comment]
The syncthing database is under `~/.var/app/com.github.zocker_160.SyncThingy/config/syncthing/index-v0.14.0.db`. 

For me personally the `.local/state` folder is empty, so I am not exactly sure why that is different for you.

**Comment by zocker-160** [comment]
I just checked on my Steam Deck and it is the same there.

**Comment by MultiKoopa** [comment]
> The syncthing database is under `~/.var/app/com.github.zocker_160.SyncThingy/config/syncthing/index-v0.14.0.db`.
> 
> For me personally the `.local/state` folder is empty, so I am not exactly sure why that is different for you.

strange. But appreciate you checking :) and I did find it in the end.

**Comment by SilverGreen93** [comment]
Hi! I am on Kubuntu 24.04 and I don't have any `~/.var/app/com.github.zocker_160.SyncThingy/config/syncthing` directory. Where is my syncthing configuration located?
