### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by ldx63** [zocker-160/SyncThingy#35]
Good morning,
I'm trying to build the project on myself but got a problem with the inclusion of dependency with SingleApplication.
I tried to include it in the "src" directory by pulling with git, but during "make" I got this error:

```
$ cmake -S . -B out
CMake Error at CMakeLists.txt:30 (add_subdirectory):
  add_subdirectory given source "src/singleapplication" which is not an
  existing directory.
```

The "singleapplication" directory exists and contains the sources of SingleApplication: it's the SingleApplication directory pulled from git, renamed in all lowercase.

I'm using Fedora 40 and all other mentioned dependencies have been installed.

I guess I am doing something wrong, but I can't figure out what.

Thank you
Aldo

**Comment by ldx63** [comment]
OK I found the solution on myself: pulling SingleApplication must be done with this command in the "src" directory:

`git submodule add https://github.com/itay-grudev/SingleApplication.git singleapplication`

and the "cmake" command works fine.

Sorry for the wrong issue opening.
Regards
Aldo

**Comment by zocker-160** [comment]
Hi,

for the record: you need to pull all submodules also to make it work. Yes the instructions in the readme are actually not correct, I will fix that.
