### ISSUE TITLE
Running as Service then Tray Icon dosn't work on Destop Mode of Steamdeck

### ISSUE THREAD

**Issue by ctempleton3** [zocker-160/SyncThingy#36]
I installed the flatpak of Syncthing wth the tray icon on my Valve Steam Deck. For thoes unfamilar with this is a Arch Linix with KDE Plasma. I wanted it to run as a service so I opened a console and copied and pasted in the commands in the tray to make it a service. I got the commands from the tray. I got no errors. Now when I boot into KDE out of gaming mode the tray icon starts and gives me a ERROR Syntch failed to start! exit code (1). If you go to the GUI both in gaming mode and in desktop mode (The KDE desktop) it works. The only thing that dosn’t work is the tray icon. Is there a way to see why the tray icon is crashing? I get the following if I run it from the tray. I can go to that web address “[http://127.0.0.1:8384/rest/noauth/health 1](http://127.0.0.1:8384/rest/noauth/health)” and it says “OK”. I assume this means it is running since the GUI works.

```
$ ./flatpak run --branch=stable --arch=x86_64 --command=SyncThingy com.github.zocker_160.SyncThingy
F: Not sharing "/esp" with sandbox: Ignoring blocking autofs path "/esp"
Qt: Session management error: Could not open network socket
config watcher running
running inside Flatpak 

Using Icon: "com.github.zocker_160.SyncThingy"
Ping endpoint:  "http://127.0.0.1:8384/rest/noauth/health"
Requesting background permission...
reply:  QJsonDocument()
syncthing is not running
Syncthing does not seem to be running, starting own instance
/app/bin/syncthing
Background / Autostart permission granted
syncthing is not running
quit triggered
```

**Comment by zocker-160** [comment]
Not sure what exactly is going on, but the log shows that the reply is empty, which is why it is assuming that it is not running.

A successful reply should log like this
`reply:  QJsonDocument({"status":"OK"})`

Usually this happens when you enable http**s** but you don't change the URL in the settings.

**Comment by ctempleton3** [comment]
So I turned off HTTPS and it works. Where do I set up the URL in the settings? I would like to turn back on HTTPS.

**Comment by ctempleton3** [comment]
Never mind I found it. You can close this.

**Comment by zocker-160** [comment]
Thank you for confirming the issue.

I won't close the issue just yet, because I will implement an automatic detection, so ppl don't run into this issue anymore. (you are not the first reporting this problem)
