### ISSUE TITLE
Provide black and white icon in tray

### ISSUE THREAD

**Issue by husim0** [zocker-160/SyncThingy#4]
Hello,

First, thank you so much about SyncThingy, it's a really cool piece of software !

On the `README`, we can see KDE Plasma system tray. All icons are black and white, but SyncThingy is not. Do you think it would be possible to provide a black and one icon for SyncThingy too ? Maybe with a tweak in a config file or I don't know.

Kindly

**Comment by zocker-160** [comment]
Thank you for the kind words! 

The reason why I selected the colored icon is because it works for almost all themes, but I hear you, I think adding an option into a small config file for `black / white / colored` is doable.

putting on my TODO

**Comment by zocker-160** [comment]
implemented in 0.3
